name: Deploy Flutter Web
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: Build Flutter web
        run: |
          flutter pub get
          flutter build web --release

      - name: Prepare Deploy
        run: |
          mkdir -p deploy
          cp -r build/web/* deploy/

      - name: Verify files
        run: ls -R deploy/

      - name: Trigger Render Deployment
        run: |
          echo "API URL: $RENDER_API_URL"
          curl -v -X POST "$RENDER_API_URL" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_API_URL: ${{ secrets.RENDER_API_URL }}
